site_name: Falling Fruit Documentation
docs_dir: 'data'

theme:
  name: material
  custom_dir: html
  logo: _assets/logo.svg
  favicon: _assets/favicon.png

plugins:
  - search
  - git-revision-date
  - awesome-pages

# css overrides
extra_css:
  - _styles/index.css

# disable edit button
edit_uri: ''

# repository link
repo_url: https://github.com/hack4impact-uiuc/falling-fruit/
repo_name: hack4impact-uiuc/falling-fruit
