site_name: Falling Fruit Documentation
nav:
  - Home: 'index.md'
  - 'VS Code':
      - 'Auto-Linting and Formatting': 'vscode/auto-linting-and-formatting.md'
      - 'General Tips': 'vscode/general-tips.md'

docs_dir: 'data'

theme:
  name: material
  custom_dir: html
  logo: _assets/logo.svg
  favicon: _assets/favicon.png

plugins:
  - search
  - git-revision-date

extra_css:
  - _styles/index.css

edit_uri: ''
repo_url: https://github.com/hack4impact-uiuc/falling-fruit/
repo_name: hack4impact-uiuc/falling-fruit
